package com.taofang.webapi.model;

import java.util.Date;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ID
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.AdvertTitle
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private String adverttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.AdvertImage
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private String advertimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.AdvertURL
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private String adverturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.CategoryType
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private Integer categorytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.CreateBy
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.CreateDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.LastModify
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private String lastmodify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.LastModifyDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    private Date lastmodifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ID
     *
     * @return the value of advertisement.ID
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ID
     *
     * @param id the value for advertisement.ID
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.AdvertTitle
     *
     * @return the value of advertisement.AdvertTitle
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public String getAdverttitle() {
        return adverttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.AdvertTitle
     *
     * @param adverttitle the value for advertisement.AdvertTitle
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setAdverttitle(String adverttitle) {
        this.adverttitle = adverttitle == null ? null : adverttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.AdvertImage
     *
     * @return the value of advertisement.AdvertImage
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public String getAdvertimage() {
        return advertimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.AdvertImage
     *
     * @param advertimage the value for advertisement.AdvertImage
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setAdvertimage(String advertimage) {
        this.advertimage = advertimage == null ? null : advertimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.AdvertURL
     *
     * @return the value of advertisement.AdvertURL
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public String getAdverturl() {
        return adverturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.AdvertURL
     *
     * @param adverturl the value for advertisement.AdvertURL
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setAdverturl(String adverturl) {
        this.adverturl = adverturl == null ? null : adverturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CategoryType
     *
     * @return the value of advertisement.CategoryType
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public Integer getCategorytype() {
        return categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CategoryType
     *
     * @param categorytype the value for advertisement.CategoryType
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setCategorytype(Integer categorytype) {
        this.categorytype = categorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CreateBy
     *
     * @return the value of advertisement.CreateBy
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CreateBy
     *
     * @param createby the value for advertisement.CreateBy
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CreateDate
     *
     * @return the value of advertisement.CreateDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CreateDate
     *
     * @param createdate the value for advertisement.CreateDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.LastModify
     *
     * @return the value of advertisement.LastModify
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public String getLastmodify() {
        return lastmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.LastModify
     *
     * @param lastmodify the value for advertisement.LastModify
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setLastmodify(String lastmodify) {
        this.lastmodify = lastmodify == null ? null : lastmodify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.LastModifyDate
     *
     * @return the value of advertisement.LastModifyDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public Date getLastmodifydate() {
        return lastmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.LastModifyDate
     *
     * @param lastmodifydate the value for advertisement.LastModifyDate
     *
     * @mbggenerated Sun May 29 19:34:05 CST 2016
     */
    public void setLastmodifydate(Date lastmodifydate) {
        this.lastmodifydate = lastmodifydate;
    }
}