package com.taofang.webapi.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ArticleID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ArticleName
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String articlename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ImageUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.LinkUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String linkurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Sequence
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.LastUpdateDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.LastUpdateUser
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Title
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.KeyWord
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Description
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CategoryID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.SetUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String seturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.IsProgramEncyclopedia
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String isprogramencyclopedia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.IsPrescriptionIndex
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer isprescriptionindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Disease
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String disease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Video
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.VideoDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Date videodate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Category
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.IsDTS
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private Integer isdts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ArticleID
     *
     * @return the value of article.ArticleID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ArticleID
     *
     * @param articleid the value for article.ArticleID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ArticleName
     *
     * @return the value of article.ArticleName
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getArticlename() {
        return articlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ArticleName
     *
     * @param articlename the value for article.ArticleName
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setArticlename(String articlename) {
        this.articlename = articlename == null ? null : articlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ImageUrl
     *
     * @return the value of article.ImageUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ImageUrl
     *
     * @param imageurl the value for article.ImageUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.LinkUrl
     *
     * @return the value of article.LinkUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.LinkUrl
     *
     * @param linkurl the value for article.LinkUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl == null ? null : linkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Sequence
     *
     * @return the value of article.Sequence
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Sequence
     *
     * @param sequence the value for article.Sequence
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.LastUpdateDate
     *
     * @return the value of article.LastUpdateDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.LastUpdateDate
     *
     * @param lastupdatedate the value for article.LastUpdateDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.LastUpdateUser
     *
     * @return the value of article.LastUpdateUser
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.LastUpdateUser
     *
     * @param lastupdateuser the value for article.LastUpdateUser
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Title
     *
     * @return the value of article.Title
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Title
     *
     * @param title the value for article.Title
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.KeyWord
     *
     * @return the value of article.KeyWord
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.KeyWord
     *
     * @param keyword the value for article.KeyWord
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Description
     *
     * @return the value of article.Description
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Description
     *
     * @param description the value for article.Description
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CategoryID
     *
     * @return the value of article.CategoryID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CategoryID
     *
     * @param categoryid the value for article.CategoryID
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.SetUrl
     *
     * @return the value of article.SetUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getSeturl() {
        return seturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.SetUrl
     *
     * @param seturl the value for article.SetUrl
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setSeturl(String seturl) {
        this.seturl = seturl == null ? null : seturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.IsProgramEncyclopedia
     *
     * @return the value of article.IsProgramEncyclopedia
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getIsprogramencyclopedia() {
        return isprogramencyclopedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.IsProgramEncyclopedia
     *
     * @param isprogramencyclopedia the value for article.IsProgramEncyclopedia
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setIsprogramencyclopedia(String isprogramencyclopedia) {
        this.isprogramencyclopedia = isprogramencyclopedia == null ? null : isprogramencyclopedia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.IsPrescriptionIndex
     *
     * @return the value of article.IsPrescriptionIndex
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getIsprescriptionindex() {
        return isprescriptionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.IsPrescriptionIndex
     *
     * @param isprescriptionindex the value for article.IsPrescriptionIndex
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setIsprescriptionindex(Integer isprescriptionindex) {
        this.isprescriptionindex = isprescriptionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Disease
     *
     * @return the value of article.Disease
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Disease
     *
     * @param disease the value for article.Disease
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setDisease(String disease) {
        this.disease = disease == null ? null : disease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Video
     *
     * @return the value of article.Video
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Video
     *
     * @param video the value for article.Video
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.VideoDate
     *
     * @return the value of article.VideoDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Date getVideodate() {
        return videodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.VideoDate
     *
     * @param videodate the value for article.VideoDate
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setVideodate(Date videodate) {
        this.videodate = videodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Category
     *
     * @return the value of article.Category
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Category
     *
     * @param category the value for article.Category
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.IsDTS
     *
     * @return the value of article.IsDTS
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public Integer getIsdts() {
        return isdts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.IsDTS
     *
     * @param isdts the value for article.IsDTS
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setIsdts(Integer isdts) {
        this.isdts = isdts;
    }
}