package com.taofang.webapi.model;

public class ArticleWithBLOBs extends Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ArticleContent
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String articlecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Summary
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.Symptom
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    private String symptom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ArticleContent
     *
     * @return the value of article.ArticleContent
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getArticlecontent() {
        return articlecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ArticleContent
     *
     * @param articlecontent the value for article.ArticleContent
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setArticlecontent(String articlecontent) {
        this.articlecontent = articlecontent == null ? null : articlecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Summary
     *
     * @return the value of article.Summary
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Summary
     *
     * @param summary the value for article.Summary
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.Symptom
     *
     * @return the value of article.Symptom
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.Symptom
     *
     * @param symptom the value for article.Symptom
     *
     * @mbggenerated Sat May 07 19:53:23 CST 2016
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }
}