package com.taofang.webapi.model;

public class CommentstarWithBLOBs extends Commentstar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Experience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Images
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private String images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Experience
     *
     * @return the value of commentstar.Experience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Experience
     *
     * @param experience the value for commentstar.Experience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Images
     *
     * @return the value of commentstar.Images
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Images
     *
     * @param images the value for commentstar.Images
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }
}