package com.taofang.webapi.model;

import java.util.Date;

public class Commentstar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.CommentID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.PrescriptionID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Integer prescriptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Sequence
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.MemberID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.IsShowName
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private String isshowname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.EffectiveDegree
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double effectivedegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.EffectiveSpeed
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double effectivespeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Security
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double security;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Convenience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double convenience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.SaveMoney
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Double savemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.CreatedDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.Status
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.LastUpdateUser
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentstar.LastUpdateDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.CommentID
     *
     * @return the value of commentstar.CommentID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.CommentID
     *
     * @param commentid the value for commentstar.CommentID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setCommentid(Double commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.PrescriptionID
     *
     * @return the value of commentstar.PrescriptionID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Integer getPrescriptionid() {
        return prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.PrescriptionID
     *
     * @param prescriptionid the value for commentstar.PrescriptionID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setPrescriptionid(Integer prescriptionid) {
        this.prescriptionid = prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Sequence
     *
     * @return the value of commentstar.Sequence
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Sequence
     *
     * @param sequence the value for commentstar.Sequence
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.MemberID
     *
     * @return the value of commentstar.MemberID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.MemberID
     *
     * @param memberid the value for commentstar.MemberID
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.IsShowName
     *
     * @return the value of commentstar.IsShowName
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public String getIsshowname() {
        return isshowname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.IsShowName
     *
     * @param isshowname the value for commentstar.IsShowName
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setIsshowname(String isshowname) {
        this.isshowname = isshowname == null ? null : isshowname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.EffectiveDegree
     *
     * @return the value of commentstar.EffectiveDegree
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getEffectivedegree() {
        return effectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.EffectiveDegree
     *
     * @param effectivedegree the value for commentstar.EffectiveDegree
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setEffectivedegree(Double effectivedegree) {
        this.effectivedegree = effectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.EffectiveSpeed
     *
     * @return the value of commentstar.EffectiveSpeed
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getEffectivespeed() {
        return effectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.EffectiveSpeed
     *
     * @param effectivespeed the value for commentstar.EffectiveSpeed
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setEffectivespeed(Double effectivespeed) {
        this.effectivespeed = effectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Security
     *
     * @return the value of commentstar.Security
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getSecurity() {
        return security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Security
     *
     * @param security the value for commentstar.Security
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setSecurity(Double security) {
        this.security = security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Convenience
     *
     * @return the value of commentstar.Convenience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getConvenience() {
        return convenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Convenience
     *
     * @param convenience the value for commentstar.Convenience
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setConvenience(Double convenience) {
        this.convenience = convenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.SaveMoney
     *
     * @return the value of commentstar.SaveMoney
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Double getSavemoney() {
        return savemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.SaveMoney
     *
     * @param savemoney the value for commentstar.SaveMoney
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setSavemoney(Double savemoney) {
        this.savemoney = savemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.CreatedDate
     *
     * @return the value of commentstar.CreatedDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.CreatedDate
     *
     * @param createddate the value for commentstar.CreatedDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.Status
     *
     * @return the value of commentstar.Status
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.Status
     *
     * @param status the value for commentstar.Status
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.LastUpdateUser
     *
     * @return the value of commentstar.LastUpdateUser
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.LastUpdateUser
     *
     * @param lastupdateuser the value for commentstar.LastUpdateUser
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentstar.LastUpdateDate
     *
     * @return the value of commentstar.LastUpdateDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentstar.LastUpdateDate
     *
     * @param lastupdatedate the value for commentstar.LastUpdateDate
     *
     * @mbggenerated Sun May 08 22:33:22 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}