package com.taofang.webapi.model;

import java.util.Date;

public class Disease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseaseID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Double diseaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.Sex
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.Letter
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.DiseaseName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String diseasename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.AliasName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String aliasname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.CreateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.CreateBy
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.LastUpdateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.LastUpdateUser
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.Sequence
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.IsCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String iscommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.ImageURL
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.IsInquiryCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Integer isinquirycommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.TypeID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.Hide
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    private String hide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseaseID
     *
     * @return the value of disease.DiseaseID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Double getDiseaseid() {
        return diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseaseID
     *
     * @param diseaseid the value for disease.DiseaseID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setDiseaseid(Double diseaseid) {
        this.diseaseid = diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.Sex
     *
     * @return the value of disease.Sex
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.Sex
     *
     * @param sex the value for disease.Sex
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.Letter
     *
     * @return the value of disease.Letter
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getLetter() {
        return letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.Letter
     *
     * @param letter the value for disease.Letter
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setLetter(String letter) {
        this.letter = letter == null ? null : letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.DiseaseName
     *
     * @return the value of disease.DiseaseName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getDiseasename() {
        return diseasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.DiseaseName
     *
     * @param diseasename the value for disease.DiseaseName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setDiseasename(String diseasename) {
        this.diseasename = diseasename == null ? null : diseasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.AliasName
     *
     * @return the value of disease.AliasName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getAliasname() {
        return aliasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.AliasName
     *
     * @param aliasname the value for disease.AliasName
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setAliasname(String aliasname) {
        this.aliasname = aliasname == null ? null : aliasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.CreateDate
     *
     * @return the value of disease.CreateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.CreateDate
     *
     * @param createdate the value for disease.CreateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.CreateBy
     *
     * @return the value of disease.CreateBy
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.CreateBy
     *
     * @param createby the value for disease.CreateBy
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.LastUpdateDate
     *
     * @return the value of disease.LastUpdateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.LastUpdateDate
     *
     * @param lastupdatedate the value for disease.LastUpdateDate
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.LastUpdateUser
     *
     * @return the value of disease.LastUpdateUser
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.LastUpdateUser
     *
     * @param lastupdateuser the value for disease.LastUpdateUser
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.Sequence
     *
     * @return the value of disease.Sequence
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.Sequence
     *
     * @param sequence the value for disease.Sequence
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.IsCommon
     *
     * @return the value of disease.IsCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getIscommon() {
        return iscommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.IsCommon
     *
     * @param iscommon the value for disease.IsCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setIscommon(String iscommon) {
        this.iscommon = iscommon == null ? null : iscommon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.ImageURL
     *
     * @return the value of disease.ImageURL
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.ImageURL
     *
     * @param imageurl the value for disease.ImageURL
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.IsInquiryCommon
     *
     * @return the value of disease.IsInquiryCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Integer getIsinquirycommon() {
        return isinquirycommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.IsInquiryCommon
     *
     * @param isinquirycommon the value for disease.IsInquiryCommon
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setIsinquirycommon(Integer isinquirycommon) {
        this.isinquirycommon = isinquirycommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.TypeID
     *
     * @return the value of disease.TypeID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.TypeID
     *
     * @param typeid the value for disease.TypeID
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.Hide
     *
     * @return the value of disease.Hide
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public String getHide() {
        return hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.Hide
     *
     * @param hide the value for disease.Hide
     *
     * @mbggenerated Wed Apr 06 22:16:00 CST 2016
     */
    public void setHide(String hide) {
        this.hide = hide == null ? null : hide.trim();
    }
}