package com.taofang.webapi.model;

import java.util.Date;

public class Dtsimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.ID
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Sequence
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Title
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Image
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Music
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String music;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.CreateBy
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.CreateDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.LastModify
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String lastmodify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.LastModifyDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private Date lastmodifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Video
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Category
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtsimage.Detail
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.ID
     *
     * @return the value of dtsimage.ID
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.ID
     *
     * @param id the value for dtsimage.ID
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Sequence
     *
     * @return the value of dtsimage.Sequence
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Sequence
     *
     * @param sequence the value for dtsimage.Sequence
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Title
     *
     * @return the value of dtsimage.Title
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Title
     *
     * @param title the value for dtsimage.Title
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Image
     *
     * @return the value of dtsimage.Image
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Image
     *
     * @param image the value for dtsimage.Image
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Music
     *
     * @return the value of dtsimage.Music
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getMusic() {
        return music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Music
     *
     * @param music the value for dtsimage.Music
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setMusic(String music) {
        this.music = music == null ? null : music.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.CreateBy
     *
     * @return the value of dtsimage.CreateBy
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.CreateBy
     *
     * @param createby the value for dtsimage.CreateBy
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.CreateDate
     *
     * @return the value of dtsimage.CreateDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.CreateDate
     *
     * @param createdate the value for dtsimage.CreateDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.LastModify
     *
     * @return the value of dtsimage.LastModify
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getLastmodify() {
        return lastmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.LastModify
     *
     * @param lastmodify the value for dtsimage.LastModify
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setLastmodify(String lastmodify) {
        this.lastmodify = lastmodify == null ? null : lastmodify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.LastModifyDate
     *
     * @return the value of dtsimage.LastModifyDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public Date getLastmodifydate() {
        return lastmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.LastModifyDate
     *
     * @param lastmodifydate the value for dtsimage.LastModifyDate
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setLastmodifydate(Date lastmodifydate) {
        this.lastmodifydate = lastmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Video
     *
     * @return the value of dtsimage.Video
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Video
     *
     * @param video the value for dtsimage.Video
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Category
     *
     * @return the value of dtsimage.Category
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Category
     *
     * @param category the value for dtsimage.Category
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtsimage.Detail
     *
     * @return the value of dtsimage.Detail
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtsimage.Detail
     *
     * @param detail the value for dtsimage.Detail
     *
     * @mbggenerated Sat May 07 18:19:12 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}