package com.taofang.webapi.model;

public class InquiryprescriptionWithBLOBs extends Inquiryprescription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Description
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Images
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Description
     *
     * @return the value of inquiryprescription.Description
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Description
     *
     * @param description the value for inquiryprescription.Description
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Images
     *
     * @return the value of inquiryprescription.Images
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Images
     *
     * @param images the value for inquiryprescription.Images
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }
}