package com.taofang.webapi.model;

import java.util.Date;

public class Inquiryprescription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.InquiryID
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Double inquiryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Title
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.SymptomIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String symptomids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.DiseaseIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String diseaseids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.DiseaseNames
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String diseasenames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.UndergoneTreatment
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String undergonetreatment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.TreatmentOutcome
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String treatmentoutcome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.ForHelp
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String forhelp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Sex
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.BirthYear
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Integer birthyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.BirthMonth
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Integer birthmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Phone
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Anonymous
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String anonymous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Status
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.CreatedBy
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Integer createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.CreatedDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.Visited
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Integer visited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.InquiryStatus
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private String inquirystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiryprescription.LastReplyDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    private Date lastreplydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.InquiryID
     *
     * @return the value of inquiryprescription.InquiryID
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Double getInquiryid() {
        return inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.InquiryID
     *
     * @param inquiryid the value for inquiryprescription.InquiryID
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setInquiryid(Double inquiryid) {
        this.inquiryid = inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Title
     *
     * @return the value of inquiryprescription.Title
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Title
     *
     * @param title the value for inquiryprescription.Title
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.SymptomIDs
     *
     * @return the value of inquiryprescription.SymptomIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getSymptomids() {
        return symptomids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.SymptomIDs
     *
     * @param symptomids the value for inquiryprescription.SymptomIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setSymptomids(String symptomids) {
        this.symptomids = symptomids == null ? null : symptomids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.DiseaseIDs
     *
     * @return the value of inquiryprescription.DiseaseIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getDiseaseids() {
        return diseaseids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.DiseaseIDs
     *
     * @param diseaseids the value for inquiryprescription.DiseaseIDs
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setDiseaseids(String diseaseids) {
        this.diseaseids = diseaseids == null ? null : diseaseids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.DiseaseNames
     *
     * @return the value of inquiryprescription.DiseaseNames
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getDiseasenames() {
        return diseasenames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.DiseaseNames
     *
     * @param diseasenames the value for inquiryprescription.DiseaseNames
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setDiseasenames(String diseasenames) {
        this.diseasenames = diseasenames == null ? null : diseasenames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.UndergoneTreatment
     *
     * @return the value of inquiryprescription.UndergoneTreatment
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getUndergonetreatment() {
        return undergonetreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.UndergoneTreatment
     *
     * @param undergonetreatment the value for inquiryprescription.UndergoneTreatment
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setUndergonetreatment(String undergonetreatment) {
        this.undergonetreatment = undergonetreatment == null ? null : undergonetreatment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.TreatmentOutcome
     *
     * @return the value of inquiryprescription.TreatmentOutcome
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getTreatmentoutcome() {
        return treatmentoutcome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.TreatmentOutcome
     *
     * @param treatmentoutcome the value for inquiryprescription.TreatmentOutcome
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setTreatmentoutcome(String treatmentoutcome) {
        this.treatmentoutcome = treatmentoutcome == null ? null : treatmentoutcome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.ForHelp
     *
     * @return the value of inquiryprescription.ForHelp
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getForhelp() {
        return forhelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.ForHelp
     *
     * @param forhelp the value for inquiryprescription.ForHelp
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setForhelp(String forhelp) {
        this.forhelp = forhelp == null ? null : forhelp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Sex
     *
     * @return the value of inquiryprescription.Sex
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Sex
     *
     * @param sex the value for inquiryprescription.Sex
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.BirthYear
     *
     * @return the value of inquiryprescription.BirthYear
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Integer getBirthyear() {
        return birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.BirthYear
     *
     * @param birthyear the value for inquiryprescription.BirthYear
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setBirthyear(Integer birthyear) {
        this.birthyear = birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.BirthMonth
     *
     * @return the value of inquiryprescription.BirthMonth
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Integer getBirthmonth() {
        return birthmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.BirthMonth
     *
     * @param birthmonth the value for inquiryprescription.BirthMonth
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setBirthmonth(Integer birthmonth) {
        this.birthmonth = birthmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Phone
     *
     * @return the value of inquiryprescription.Phone
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Phone
     *
     * @param phone the value for inquiryprescription.Phone
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Anonymous
     *
     * @return the value of inquiryprescription.Anonymous
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getAnonymous() {
        return anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Anonymous
     *
     * @param anonymous the value for inquiryprescription.Anonymous
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setAnonymous(String anonymous) {
        this.anonymous = anonymous == null ? null : anonymous.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Status
     *
     * @return the value of inquiryprescription.Status
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Status
     *
     * @param status the value for inquiryprescription.Status
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.CreatedBy
     *
     * @return the value of inquiryprescription.CreatedBy
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Integer getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.CreatedBy
     *
     * @param createdby the value for inquiryprescription.CreatedBy
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.CreatedDate
     *
     * @return the value of inquiryprescription.CreatedDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.CreatedDate
     *
     * @param createddate the value for inquiryprescription.CreatedDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.LastUpdateUser
     *
     * @return the value of inquiryprescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.LastUpdateUser
     *
     * @param lastupdateuser the value for inquiryprescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.LastUpdateDate
     *
     * @return the value of inquiryprescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.LastUpdateDate
     *
     * @param lastupdatedate the value for inquiryprescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.Visited
     *
     * @return the value of inquiryprescription.Visited
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Integer getVisited() {
        return visited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.Visited
     *
     * @param visited the value for inquiryprescription.Visited
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setVisited(Integer visited) {
        this.visited = visited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.InquiryStatus
     *
     * @return the value of inquiryprescription.InquiryStatus
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public String getInquirystatus() {
        return inquirystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.InquiryStatus
     *
     * @param inquirystatus the value for inquiryprescription.InquiryStatus
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setInquirystatus(String inquirystatus) {
        this.inquirystatus = inquirystatus == null ? null : inquirystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiryprescription.LastReplyDate
     *
     * @return the value of inquiryprescription.LastReplyDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public Date getLastreplydate() {
        return lastreplydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiryprescription.LastReplyDate
     *
     * @param lastreplydate the value for inquiryprescription.LastReplyDate
     *
     * @mbggenerated Sun May 15 17:57:19 CST 2016
     */
    public void setLastreplydate(Date lastreplydate) {
        this.lastreplydate = lastreplydate;
    }
}