package com.taofang.webapi.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.MemberID
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.MemberName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String membername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Password
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Email
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Phone
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Age
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Sex
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.RegisterDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Date registerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Status
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Description
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.SkillName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String skillname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Credits
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Integer credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ApplyExpertTime
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Date applyexperttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ApplyExpertStatus
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String applyexpertstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.MemberType
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String membertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Hospital
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.LastUpdateUser
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.LastUpdateDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Image
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.NickName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.RealName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Birthday
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Province
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.City
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.County
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Address
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.IdentityNumber
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String identitynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Icon
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.MemberID
     *
     * @return the value of member.MemberID
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.MemberID
     *
     * @param memberid the value for member.MemberID
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.MemberName
     *
     * @return the value of member.MemberName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.MemberName
     *
     * @param membername the value for member.MemberName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setMembername(String membername) {
        this.membername = membername == null ? null : membername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Password
     *
     * @return the value of member.Password
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Password
     *
     * @param password the value for member.Password
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Email
     *
     * @return the value of member.Email
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Email
     *
     * @param email the value for member.Email
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Phone
     *
     * @return the value of member.Phone
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Phone
     *
     * @param phone the value for member.Phone
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Age
     *
     * @return the value of member.Age
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Age
     *
     * @param age the value for member.Age
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Sex
     *
     * @return the value of member.Sex
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Sex
     *
     * @param sex the value for member.Sex
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.RegisterDate
     *
     * @return the value of member.RegisterDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.RegisterDate
     *
     * @param registerdate the value for member.RegisterDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Status
     *
     * @return the value of member.Status
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Status
     *
     * @param status the value for member.Status
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Description
     *
     * @return the value of member.Description
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Description
     *
     * @param description the value for member.Description
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.SkillName
     *
     * @return the value of member.SkillName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getSkillname() {
        return skillname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.SkillName
     *
     * @param skillname the value for member.SkillName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setSkillname(String skillname) {
        this.skillname = skillname == null ? null : skillname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Credits
     *
     * @return the value of member.Credits
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Credits
     *
     * @param credits the value for member.Credits
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ApplyExpertTime
     *
     * @return the value of member.ApplyExpertTime
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Date getApplyexperttime() {
        return applyexperttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ApplyExpertTime
     *
     * @param applyexperttime the value for member.ApplyExpertTime
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setApplyexperttime(Date applyexperttime) {
        this.applyexperttime = applyexperttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ApplyExpertStatus
     *
     * @return the value of member.ApplyExpertStatus
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getApplyexpertstatus() {
        return applyexpertstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ApplyExpertStatus
     *
     * @param applyexpertstatus the value for member.ApplyExpertStatus
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setApplyexpertstatus(String applyexpertstatus) {
        this.applyexpertstatus = applyexpertstatus == null ? null : applyexpertstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.MemberType
     *
     * @return the value of member.MemberType
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getMembertype() {
        return membertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.MemberType
     *
     * @param membertype the value for member.MemberType
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setMembertype(String membertype) {
        this.membertype = membertype == null ? null : membertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Hospital
     *
     * @return the value of member.Hospital
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Hospital
     *
     * @param hospital the value for member.Hospital
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.LastUpdateUser
     *
     * @return the value of member.LastUpdateUser
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.LastUpdateUser
     *
     * @param lastupdateuser the value for member.LastUpdateUser
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.LastUpdateDate
     *
     * @return the value of member.LastUpdateDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.LastUpdateDate
     *
     * @param lastupdatedate the value for member.LastUpdateDate
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Image
     *
     * @return the value of member.Image
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Image
     *
     * @param image the value for member.Image
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.NickName
     *
     * @return the value of member.NickName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.NickName
     *
     * @param nickname the value for member.NickName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.RealName
     *
     * @return the value of member.RealName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.RealName
     *
     * @param realname the value for member.RealName
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Birthday
     *
     * @return the value of member.Birthday
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Birthday
     *
     * @param birthday the value for member.Birthday
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Province
     *
     * @return the value of member.Province
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Province
     *
     * @param province the value for member.Province
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.City
     *
     * @return the value of member.City
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.City
     *
     * @param city the value for member.City
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.County
     *
     * @return the value of member.County
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.County
     *
     * @param county the value for member.County
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Address
     *
     * @return the value of member.Address
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Address
     *
     * @param address the value for member.Address
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.IdentityNumber
     *
     * @return the value of member.IdentityNumber
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getIdentitynumber() {
        return identitynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.IdentityNumber
     *
     * @param identitynumber the value for member.IdentityNumber
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setIdentitynumber(String identitynumber) {
        this.identitynumber = identitynumber == null ? null : identitynumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Icon
     *
     * @return the value of member.Icon
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Icon
     *
     * @param icon the value for member.Icon
     *
     * @mbggenerated Mon Apr 11 11:03:50 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}