package com.taofang.webapi.model;

public class Prescriptionmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.PrescriptionID
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private Integer prescriptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Name
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.AliasName
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String aliasname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.MaterialCollection
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String materialcollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Title
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.KeyWord
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Description
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Audio
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String audio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.PrescriptionID
     *
     * @return the value of prescriptionmessage.PrescriptionID
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public Integer getPrescriptionid() {
        return prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.PrescriptionID
     *
     * @param prescriptionid the value for prescriptionmessage.PrescriptionID
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setPrescriptionid(Integer prescriptionid) {
        this.prescriptionid = prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Name
     *
     * @return the value of prescriptionmessage.Name
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Name
     *
     * @param name the value for prescriptionmessage.Name
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.AliasName
     *
     * @return the value of prescriptionmessage.AliasName
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getAliasname() {
        return aliasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.AliasName
     *
     * @param aliasname the value for prescriptionmessage.AliasName
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setAliasname(String aliasname) {
        this.aliasname = aliasname == null ? null : aliasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.MaterialCollection
     *
     * @return the value of prescriptionmessage.MaterialCollection
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getMaterialcollection() {
        return materialcollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.MaterialCollection
     *
     * @param materialcollection the value for prescriptionmessage.MaterialCollection
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setMaterialcollection(String materialcollection) {
        this.materialcollection = materialcollection == null ? null : materialcollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Title
     *
     * @return the value of prescriptionmessage.Title
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Title
     *
     * @param title the value for prescriptionmessage.Title
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.KeyWord
     *
     * @return the value of prescriptionmessage.KeyWord
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.KeyWord
     *
     * @param keyword the value for prescriptionmessage.KeyWord
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Description
     *
     * @return the value of prescriptionmessage.Description
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Description
     *
     * @param description the value for prescriptionmessage.Description
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Audio
     *
     * @return the value of prescriptionmessage.Audio
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Audio
     *
     * @param audio the value for prescriptionmessage.Audio
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setAudio(String audio) {
        this.audio = audio == null ? null : audio.trim();
    }
}