package com.taofang.webapi.model;

import java.util.Date;

public class Prescription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PrescriptionID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Integer prescriptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ImageURL
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Letter
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Status
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.CreateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ISAuditing
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String isauditing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String lastupdateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.CreatorName
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String creatorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.IsAudited
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String isaudited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.IsFront
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String isfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.InquiryID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double inquiryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Score
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.EffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double effectivedegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.EffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double effectivespeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.SaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double savemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TotalEffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double totaleffectivedegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TotalEffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double totaleffectivespeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TotalSecurity
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double totalsecurity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TotalConvenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double totalconvenience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TotalSaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double totalsavemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.CommentNumber
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double commentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ED1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double ed1number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ED2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double ed2number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ED3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double ed3number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ED4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double ed4number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ED5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double ed5number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ES1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double es1number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ES2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double es2number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ES3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double es3number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ES4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double es4number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ES5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double es5number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security1number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security2number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security3number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security4number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Security5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double security5number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience1number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience2number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience3number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience4number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Convenience5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double convenience5number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Save1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double save1number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Save2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double save2number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Save3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double save3number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Save4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double save4number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Save5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Double save5number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PrescriptionType
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Integer prescriptiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.Hide
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String hide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.BrowseCount
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private Integer browsecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.MaterialImageOne
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    private String materialimageone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PrescriptionID
     *
     * @return the value of prescription.PrescriptionID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Integer getPrescriptionid() {
        return prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PrescriptionID
     *
     * @param prescriptionid the value for prescription.PrescriptionID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setPrescriptionid(Integer prescriptionid) {
        this.prescriptionid = prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ImageURL
     *
     * @return the value of prescription.ImageURL
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ImageURL
     *
     * @param imageurl the value for prescription.ImageURL
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Letter
     *
     * @return the value of prescription.Letter
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getLetter() {
        return letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Letter
     *
     * @param letter the value for prescription.Letter
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setLetter(String letter) {
        this.letter = letter == null ? null : letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Status
     *
     * @return the value of prescription.Status
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Status
     *
     * @param status the value for prescription.Status
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.CreateDate
     *
     * @return the value of prescription.CreateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.CreateDate
     *
     * @param createdate the value for prescription.CreateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ISAuditing
     *
     * @return the value of prescription.ISAuditing
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getIsauditing() {
        return isauditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ISAuditing
     *
     * @param isauditing the value for prescription.ISAuditing
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setIsauditing(String isauditing) {
        this.isauditing = isauditing == null ? null : isauditing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.LastUpdateUser
     *
     * @return the value of prescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.LastUpdateUser
     *
     * @param lastupdateuser the value for prescription.LastUpdateUser
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.LastUpdateDate
     *
     * @return the value of prescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.LastUpdateDate
     *
     * @param lastupdatedate the value for prescription.LastUpdateDate
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.CreatorName
     *
     * @return the value of prescription.CreatorName
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getCreatorname() {
        return creatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.CreatorName
     *
     * @param creatorname the value for prescription.CreatorName
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setCreatorname(String creatorname) {
        this.creatorname = creatorname == null ? null : creatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.IsAudited
     *
     * @return the value of prescription.IsAudited
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getIsaudited() {
        return isaudited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.IsAudited
     *
     * @param isaudited the value for prescription.IsAudited
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setIsaudited(String isaudited) {
        this.isaudited = isaudited == null ? null : isaudited.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.IsFront
     *
     * @return the value of prescription.IsFront
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getIsfront() {
        return isfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.IsFront
     *
     * @param isfront the value for prescription.IsFront
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setIsfront(String isfront) {
        this.isfront = isfront == null ? null : isfront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.InquiryID
     *
     * @return the value of prescription.InquiryID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getInquiryid() {
        return inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.InquiryID
     *
     * @param inquiryid the value for prescription.InquiryID
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setInquiryid(Double inquiryid) {
        this.inquiryid = inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Score
     *
     * @return the value of prescription.Score
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Score
     *
     * @param score the value for prescription.Score
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.EffectiveDegree
     *
     * @return the value of prescription.EffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEffectivedegree() {
        return effectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.EffectiveDegree
     *
     * @param effectivedegree the value for prescription.EffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEffectivedegree(Double effectivedegree) {
        this.effectivedegree = effectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.EffectiveSpeed
     *
     * @return the value of prescription.EffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEffectivespeed() {
        return effectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.EffectiveSpeed
     *
     * @param effectivespeed the value for prescription.EffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEffectivespeed(Double effectivespeed) {
        this.effectivespeed = effectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security
     *
     * @return the value of prescription.Security
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity() {
        return security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security
     *
     * @param security the value for prescription.Security
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity(Double security) {
        this.security = security;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience
     *
     * @return the value of prescription.Convenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience() {
        return convenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience
     *
     * @param convenience the value for prescription.Convenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience(Double convenience) {
        this.convenience = convenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.SaveMoney
     *
     * @return the value of prescription.SaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSavemoney() {
        return savemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.SaveMoney
     *
     * @param savemoney the value for prescription.SaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSavemoney(Double savemoney) {
        this.savemoney = savemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TotalEffectiveDegree
     *
     * @return the value of prescription.TotalEffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getTotaleffectivedegree() {
        return totaleffectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TotalEffectiveDegree
     *
     * @param totaleffectivedegree the value for prescription.TotalEffectiveDegree
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setTotaleffectivedegree(Double totaleffectivedegree) {
        this.totaleffectivedegree = totaleffectivedegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TotalEffectiveSpeed
     *
     * @return the value of prescription.TotalEffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getTotaleffectivespeed() {
        return totaleffectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TotalEffectiveSpeed
     *
     * @param totaleffectivespeed the value for prescription.TotalEffectiveSpeed
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setTotaleffectivespeed(Double totaleffectivespeed) {
        this.totaleffectivespeed = totaleffectivespeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TotalSecurity
     *
     * @return the value of prescription.TotalSecurity
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getTotalsecurity() {
        return totalsecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TotalSecurity
     *
     * @param totalsecurity the value for prescription.TotalSecurity
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setTotalsecurity(Double totalsecurity) {
        this.totalsecurity = totalsecurity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TotalConvenience
     *
     * @return the value of prescription.TotalConvenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getTotalconvenience() {
        return totalconvenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TotalConvenience
     *
     * @param totalconvenience the value for prescription.TotalConvenience
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setTotalconvenience(Double totalconvenience) {
        this.totalconvenience = totalconvenience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TotalSaveMoney
     *
     * @return the value of prescription.TotalSaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getTotalsavemoney() {
        return totalsavemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TotalSaveMoney
     *
     * @param totalsavemoney the value for prescription.TotalSaveMoney
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setTotalsavemoney(Double totalsavemoney) {
        this.totalsavemoney = totalsavemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.CommentNumber
     *
     * @return the value of prescription.CommentNumber
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getCommentnumber() {
        return commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.CommentNumber
     *
     * @param commentnumber the value for prescription.CommentNumber
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setCommentnumber(Double commentnumber) {
        this.commentnumber = commentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ED1Number
     *
     * @return the value of prescription.ED1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEd1number() {
        return ed1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ED1Number
     *
     * @param ed1number the value for prescription.ED1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEd1number(Double ed1number) {
        this.ed1number = ed1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ED2Number
     *
     * @return the value of prescription.ED2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEd2number() {
        return ed2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ED2Number
     *
     * @param ed2number the value for prescription.ED2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEd2number(Double ed2number) {
        this.ed2number = ed2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ED3Number
     *
     * @return the value of prescription.ED3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEd3number() {
        return ed3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ED3Number
     *
     * @param ed3number the value for prescription.ED3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEd3number(Double ed3number) {
        this.ed3number = ed3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ED4Number
     *
     * @return the value of prescription.ED4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEd4number() {
        return ed4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ED4Number
     *
     * @param ed4number the value for prescription.ED4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEd4number(Double ed4number) {
        this.ed4number = ed4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ED5Number
     *
     * @return the value of prescription.ED5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEd5number() {
        return ed5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ED5Number
     *
     * @param ed5number the value for prescription.ED5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEd5number(Double ed5number) {
        this.ed5number = ed5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ES1Number
     *
     * @return the value of prescription.ES1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEs1number() {
        return es1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ES1Number
     *
     * @param es1number the value for prescription.ES1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEs1number(Double es1number) {
        this.es1number = es1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ES2Number
     *
     * @return the value of prescription.ES2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEs2number() {
        return es2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ES2Number
     *
     * @param es2number the value for prescription.ES2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEs2number(Double es2number) {
        this.es2number = es2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ES3Number
     *
     * @return the value of prescription.ES3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEs3number() {
        return es3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ES3Number
     *
     * @param es3number the value for prescription.ES3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEs3number(Double es3number) {
        this.es3number = es3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ES4Number
     *
     * @return the value of prescription.ES4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEs4number() {
        return es4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ES4Number
     *
     * @param es4number the value for prescription.ES4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEs4number(Double es4number) {
        this.es4number = es4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ES5Number
     *
     * @return the value of prescription.ES5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getEs5number() {
        return es5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ES5Number
     *
     * @param es5number the value for prescription.ES5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setEs5number(Double es5number) {
        this.es5number = es5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security1Number
     *
     * @return the value of prescription.Security1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity1number() {
        return security1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security1Number
     *
     * @param security1number the value for prescription.Security1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity1number(Double security1number) {
        this.security1number = security1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security2Number
     *
     * @return the value of prescription.Security2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity2number() {
        return security2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security2Number
     *
     * @param security2number the value for prescription.Security2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity2number(Double security2number) {
        this.security2number = security2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security3Number
     *
     * @return the value of prescription.Security3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity3number() {
        return security3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security3Number
     *
     * @param security3number the value for prescription.Security3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity3number(Double security3number) {
        this.security3number = security3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security4Number
     *
     * @return the value of prescription.Security4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity4number() {
        return security4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security4Number
     *
     * @param security4number the value for prescription.Security4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity4number(Double security4number) {
        this.security4number = security4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Security5Number
     *
     * @return the value of prescription.Security5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSecurity5number() {
        return security5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Security5Number
     *
     * @param security5number the value for prescription.Security5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSecurity5number(Double security5number) {
        this.security5number = security5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience1Number
     *
     * @return the value of prescription.Convenience1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience1number() {
        return convenience1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience1Number
     *
     * @param convenience1number the value for prescription.Convenience1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience1number(Double convenience1number) {
        this.convenience1number = convenience1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience2Number
     *
     * @return the value of prescription.Convenience2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience2number() {
        return convenience2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience2Number
     *
     * @param convenience2number the value for prescription.Convenience2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience2number(Double convenience2number) {
        this.convenience2number = convenience2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience3Number
     *
     * @return the value of prescription.Convenience3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience3number() {
        return convenience3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience3Number
     *
     * @param convenience3number the value for prescription.Convenience3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience3number(Double convenience3number) {
        this.convenience3number = convenience3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience4Number
     *
     * @return the value of prescription.Convenience4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience4number() {
        return convenience4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience4Number
     *
     * @param convenience4number the value for prescription.Convenience4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience4number(Double convenience4number) {
        this.convenience4number = convenience4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Convenience5Number
     *
     * @return the value of prescription.Convenience5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getConvenience5number() {
        return convenience5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Convenience5Number
     *
     * @param convenience5number the value for prescription.Convenience5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setConvenience5number(Double convenience5number) {
        this.convenience5number = convenience5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Save1Number
     *
     * @return the value of prescription.Save1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSave1number() {
        return save1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Save1Number
     *
     * @param save1number the value for prescription.Save1Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSave1number(Double save1number) {
        this.save1number = save1number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Save2Number
     *
     * @return the value of prescription.Save2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSave2number() {
        return save2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Save2Number
     *
     * @param save2number the value for prescription.Save2Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSave2number(Double save2number) {
        this.save2number = save2number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Save3Number
     *
     * @return the value of prescription.Save3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSave3number() {
        return save3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Save3Number
     *
     * @param save3number the value for prescription.Save3Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSave3number(Double save3number) {
        this.save3number = save3number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Save4Number
     *
     * @return the value of prescription.Save4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSave4number() {
        return save4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Save4Number
     *
     * @param save4number the value for prescription.Save4Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSave4number(Double save4number) {
        this.save4number = save4number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Save5Number
     *
     * @return the value of prescription.Save5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Double getSave5number() {
        return save5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Save5Number
     *
     * @param save5number the value for prescription.Save5Number
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setSave5number(Double save5number) {
        this.save5number = save5number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PrescriptionType
     *
     * @return the value of prescription.PrescriptionType
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Integer getPrescriptiontype() {
        return prescriptiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PrescriptionType
     *
     * @param prescriptiontype the value for prescription.PrescriptionType
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setPrescriptiontype(Integer prescriptiontype) {
        this.prescriptiontype = prescriptiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.Hide
     *
     * @return the value of prescription.Hide
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getHide() {
        return hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.Hide
     *
     * @param hide the value for prescription.Hide
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setHide(String hide) {
        this.hide = hide == null ? null : hide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.BrowseCount
     *
     * @return the value of prescription.BrowseCount
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public Integer getBrowsecount() {
        return browsecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.BrowseCount
     *
     * @param browsecount the value for prescription.BrowseCount
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setBrowsecount(Integer browsecount) {
        this.browsecount = browsecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.MaterialImageOne
     *
     * @return the value of prescription.MaterialImageOne
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public String getMaterialimageone() {
        return materialimageone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.MaterialImageOne
     *
     * @param materialimageone the value for prescription.MaterialImageOne
     *
     * @mbggenerated Sun May 15 18:00:57 CST 2016
     */
    public void setMaterialimageone(String materialimageone) {
        this.materialimageone = materialimageone == null ? null : materialimageone.trim();
    }
}