package com.taofang.webapi.model;

public class PrescriptionmessageWithBLOBs extends Prescriptionmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Material
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.NotMeetTheCrowd
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String notmeetthecrowd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Indication
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String indication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Effect
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String effect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.ProductionAndUsage
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String productionandusage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Attentions
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String attentions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.OperatingSteps
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String operatingsteps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.Story
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String story;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescriptionmessage.ExpertComments
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    private String expertcomments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Material
     *
     * @return the value of prescriptionmessage.Material
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Material
     *
     * @param material the value for prescriptionmessage.Material
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.NotMeetTheCrowd
     *
     * @return the value of prescriptionmessage.NotMeetTheCrowd
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getNotmeetthecrowd() {
        return notmeetthecrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.NotMeetTheCrowd
     *
     * @param notmeetthecrowd the value for prescriptionmessage.NotMeetTheCrowd
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setNotmeetthecrowd(String notmeetthecrowd) {
        this.notmeetthecrowd = notmeetthecrowd == null ? null : notmeetthecrowd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Indication
     *
     * @return the value of prescriptionmessage.Indication
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getIndication() {
        return indication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Indication
     *
     * @param indication the value for prescriptionmessage.Indication
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setIndication(String indication) {
        this.indication = indication == null ? null : indication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Effect
     *
     * @return the value of prescriptionmessage.Effect
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getEffect() {
        return effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Effect
     *
     * @param effect the value for prescriptionmessage.Effect
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setEffect(String effect) {
        this.effect = effect == null ? null : effect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.ProductionAndUsage
     *
     * @return the value of prescriptionmessage.ProductionAndUsage
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getProductionandusage() {
        return productionandusage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.ProductionAndUsage
     *
     * @param productionandusage the value for prescriptionmessage.ProductionAndUsage
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setProductionandusage(String productionandusage) {
        this.productionandusage = productionandusage == null ? null : productionandusage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Attentions
     *
     * @return the value of prescriptionmessage.Attentions
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getAttentions() {
        return attentions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Attentions
     *
     * @param attentions the value for prescriptionmessage.Attentions
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setAttentions(String attentions) {
        this.attentions = attentions == null ? null : attentions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.OperatingSteps
     *
     * @return the value of prescriptionmessage.OperatingSteps
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getOperatingsteps() {
        return operatingsteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.OperatingSteps
     *
     * @param operatingsteps the value for prescriptionmessage.OperatingSteps
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setOperatingsteps(String operatingsteps) {
        this.operatingsteps = operatingsteps == null ? null : operatingsteps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.Story
     *
     * @return the value of prescriptionmessage.Story
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getStory() {
        return story;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.Story
     *
     * @param story the value for prescriptionmessage.Story
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setStory(String story) {
        this.story = story == null ? null : story.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescriptionmessage.ExpertComments
     *
     * @return the value of prescriptionmessage.ExpertComments
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public String getExpertcomments() {
        return expertcomments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescriptionmessage.ExpertComments
     *
     * @param expertcomments the value for prescriptionmessage.ExpertComments
     *
     * @mbggenerated Sun May 08 17:36:38 CST 2016
     */
    public void setExpertcomments(String expertcomments) {
        this.expertcomments = expertcomments == null ? null : expertcomments.trim();
    }
}