package com.taofang.webapi.model;

import java.util.Date;

public class Relationlink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.ID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.SourceType
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Integer sourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.LinkTitle
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private String linktitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.LinkURL
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private String linkurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.CreateBy
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.CreateDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.LastModify
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private String lastmodify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.LastModifyDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Date lastmodifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.PrescriptionID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Integer prescriptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationlink.ArticleID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    private Integer articleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.ID
     *
     * @return the value of relationlink.ID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.ID
     *
     * @param id the value for relationlink.ID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.SourceType
     *
     * @return the value of relationlink.SourceType
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Integer getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.SourceType
     *
     * @param sourcetype the value for relationlink.SourceType
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setSourcetype(Integer sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.LinkTitle
     *
     * @return the value of relationlink.LinkTitle
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public String getLinktitle() {
        return linktitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.LinkTitle
     *
     * @param linktitle the value for relationlink.LinkTitle
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setLinktitle(String linktitle) {
        this.linktitle = linktitle == null ? null : linktitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.LinkURL
     *
     * @return the value of relationlink.LinkURL
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.LinkURL
     *
     * @param linkurl the value for relationlink.LinkURL
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl == null ? null : linkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.CreateBy
     *
     * @return the value of relationlink.CreateBy
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.CreateBy
     *
     * @param createby the value for relationlink.CreateBy
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.CreateDate
     *
     * @return the value of relationlink.CreateDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.CreateDate
     *
     * @param createdate the value for relationlink.CreateDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.LastModify
     *
     * @return the value of relationlink.LastModify
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public String getLastmodify() {
        return lastmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.LastModify
     *
     * @param lastmodify the value for relationlink.LastModify
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setLastmodify(String lastmodify) {
        this.lastmodify = lastmodify == null ? null : lastmodify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.LastModifyDate
     *
     * @return the value of relationlink.LastModifyDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Date getLastmodifydate() {
        return lastmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.LastModifyDate
     *
     * @param lastmodifydate the value for relationlink.LastModifyDate
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setLastmodifydate(Date lastmodifydate) {
        this.lastmodifydate = lastmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.PrescriptionID
     *
     * @return the value of relationlink.PrescriptionID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Integer getPrescriptionid() {
        return prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.PrescriptionID
     *
     * @param prescriptionid the value for relationlink.PrescriptionID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setPrescriptionid(Integer prescriptionid) {
        this.prescriptionid = prescriptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationlink.ArticleID
     *
     * @return the value of relationlink.ArticleID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationlink.ArticleID
     *
     * @param articleid the value for relationlink.ArticleID
     *
     * @mbggenerated Sat May 07 14:46:35 CST 2016
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }
}